### ISSUE TITLE
Implement a counter

### ISSUE THREAD

**Issue by mgrosmaninho** [CSDET10/GP3#22]
- [x] Implement a counter

- [x] Check stage capacity

**Comment by mgrosmaninho** [comment]
I still need to improve the functions.

**Comment by robertofiguz** [comment]
@mgrosmaninho 

1. should this be implemented along with mathews authorization checker? and everytime someone is allowed it increments?
2. Needs to block increments over the capacity

**Comment by mgrosmaninho** [comment]
I have created a new branch containing a view called "In / Out System" to perform the "Counter" function for the stages.
