### ISSUE TITLE
Perform final testing

### ISSUE THREAD

**Issue by mgrosmaninho** [CSDET10/GP3#35]
- [x] Perform final testing

**Comment by mgrosmaninho** [comment]
@Matthew-Chamberlain You could use the file "GP3 Test Results.xlsx" to do the final test. If you don't have time to do it, let me know, and I'll do it.

**Comment by Matthew-Chamberlain** [comment]
I'll get on it

**Comment by mgrosmaninho** [comment]
Thanks @Matthew-Chamberlain 
I'm trying to solve some issues.
