### ISSUE TITLE
Test Results: Agent size phone number, remove ID from ADD agent and VIEW

### ISSUE THREAD

**Issue by mgrosmaninho** [CSDET10/GP3#68]
Agent phone number missing 1 digit.
We have: 0203 456789
We should have: 02034 567890

**Comment by mgrosmaninho** [comment]
The contact number is accepting any kind of input (letters and digits) and with any size.

**Comment by robertofiguz** [comment]
the length I think it should accept any because numbers from different countries have different lengths. the letters... maybe accept too? because someone could type +44 etc. @mgrosmaninho  what do you think?

**Comment by mgrosmaninho** [comment]
I think we could accept any characters, and we should increase the length because now it's limited to 10 or 11 char. In the case of use +44, we need more spaces to input "Country Code". @robertofiguz

**Comment by mgrosmaninho** [comment]
I'm increasing the number of caracters from 11 to 15.

**Comment by mgrosmaninho** [comment]
Done at branch "agent-1".
