### ISSUE TITLE
Test Results: Band edit + view + delete with problem

### ISSUE THREAD

**Issue by mgrosmaninho** [CSDET10/GP3#70]
Band "Edit" button is not modifying fields and not bringing the information about the Band to be modified.

**Comment by robertofiguz** [comment]
tested it and adding a new member manually fixed it. full explanation on whatsapp. Code seams fine.

**Comment by mgrosmaninho** [comment]
@robertofiguz Name Band with 1 word appear well on the view button. Bands with 2 or more words don't.

**Comment by mgrosmaninho** [comment]
I cannot delete a band in the frontend. Give me an error message.
